### ISSUE TITLE
tendrl-notifier: error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by warrenguerin** [Tendrl/alerting#181]
Jun 20 15:45:13 prdansible01 tendrl-notifier: Traceback (most recent call last):
Jun 20 15:45:13 prdansible01 tendrl-notifier: File "/usr/lib/python2.7/site-packages/tendrl/commons/event.py", line 38, in _write
Jun 20 15:45:13 prdansible01 tendrl-notifier: self.sock.connect(self.socket_path)
Jun 20 15:45:13 prdansible01 tendrl-notifier: File "/usr/lib64/python2.7/socket.py", line 224, in meth
Jun 20 15:45:13 prdansible01 tendrl-notifier: return getattr(self._sock,name)(*args)
Jun 20 15:45:13 prdansible01 tendrl-notifier: error: [Errno 2] No such file or directory
Jun 20 15:45:13 prdansible01 tendrl-notifier: Unable to pass the message into socket.{"integration_id": null, "publisher": "notifier", "job_id": null, "timestamp": "2018-06-20T14:45:13.120967+00:00", "caller": {"function": "load_definition", "line_no": 50, "filename": "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py"}, "payload": {"message": "Load definitions (.yml) for namespace.tendrl.objects.NotificationOnlyAlert"}, "priority": "debug", "parent_id": null, "node_id": "91d2debd-a191-4988-b666-421eced2859a", "flow_id": null, "message_id": "516867c3-39f7-4a3d-90ec-09c54a63f0b7"}

--

Any idea on this error?

**Comment by shtripat** [comment]
Looks like the message socket file is not created and so the issue.
Please check if file `/var/run/tendrl/message.sock` exists. Also if the dir already exists before starting the service, remove that and then try to start tendrl-node-agent.
